export const moviesData = [
    { title: "The Matrix", rating: 7.5, category: "Action" },
    { title: "Focus", rating: 6.9, category: "Comedy" },
    { title: "The Lazarus Effect", rating: 6.4, category: "Thriller" },
    { title: "Everly", rating: 5.0, category: "Action" },
    { title: "Maps to the Stars", rating: 7.5, category: "Drama" },
    { title: "Inception", rating: 8.8, category: "Sci-Fi" },
    { title: "The Dark Knight", rating: 9.0, category: "Action" },
    { title: "Interstellar", rating: 8.6, category: "Sci-Fi" },
    { title: "Fight Club", rating: 8.8, category: "Drama" },
    { title: "Forrest Gump", rating: 8.8, category: "Drama" },
    { title: "Pulp Fiction", rating: 8.9, category: "Crime" },
    { title: "The Shawshank Redemption", rating: 9.3, category: "Drama" },
    { title: "The Godfather", rating: 9.2, category: "Crime" },
    { title: "The Godfather: Part II", rating: 9.0, category: "Crime" },
    { title: "The Dark Knight Rises", rating: 8.4, category: "Action" },
    { title: "Avengers: Endgame", rating: 8.4, category: "Action" },
    { title: "Gladiator", rating: 8.5, category: "Action" },
    { title: "The Lion King", rating: 8.5, category: "Animation" },
    { title: "Toy Story", rating: 8.3, category: "Animation" },
    { title: "Finding Nemo", rating: 8.1, category: "Animation" },
    { title: "The Silence of the Lambs", rating: 8.6, category: "Thriller" },
    { title: "Se7en", rating: 8.6, category: "Thriller" },
    { title: "The Usual Suspects", rating: 8.5, category: "Thriller" },
    { title: "Saving Private Ryan", rating: 8.6, category: "War" },
    { title: "Schindler's List", rating: 8.9, category: "History" },
    { title: "Braveheart", rating: 8.3, category: "History" },
    { title: "Titanic", rating: 7.8, category: "Romance" },
    { title: "The Notebook", rating: 7.9, category: "Romance" },
    { title: "La La Land", rating: 8.0, category: "Musical" },
    { title: "The Sound of Music", rating: 8.0, category: "Musical" },
    { title: "Jurassic Park", rating: 8.1, category: "Adventure" },
    { title: "The Avengers", rating: 8.0, category: "Action" },
    { title: "Iron Man", rating: 7.9, category: "Action" },
    { title: "Guardians of the Galaxy", rating: 8.0, category: "Sci-Fi" },
    { title: "Star Wars: Episode IV - A New Hope", rating: 8.6, category: "Sci-Fi" },
    { title: "Blade Runner 2049", rating: 8.0, category: "Sci-Fi" },
    { title: "Mad Max: Fury Road", rating: 8.1, category: "Action" },
    { title: "John Wick", rating: 7.4, category: "Action" },
    { title: "Django Unchained", rating: 8.4, category: "Western" },
    { title: "The Hateful Eight", rating: 7.8, category: "Western" }
  ];